INSERT INTO role (id,role) SELECT 1, 'ROLE_ADMIN' WHERE NOT EXISTS (SELECT 1 FROM role WHERE role = 'ROLE_ADMIN');
INSERT INTO role (id,role) SELECT 2, 'ROLE_USER'  WHERE NOT EXISTS (SELECT 1 FROM role WHERE role = 'ROLE_USER');
INSERT INTO role (id,role) SELECT 3, 'ROLE_GUEST' WHERE NOT EXISTS (SELECT 1 FROM role WHERE role = 'ROLE_GUEST');
